spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/employeemanager
    username: employeemanagerservice
    password: 69AP4QHrH""BQ,6V
    dbcp2:
      validation-query: select 1 from dual
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
